apiVersion: cloud-build-notifiers/v1
kind: SMTPNotifier
metadata:
  name: example-smtp-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      server: smtp.gmail.com
      port: "587"
      sender: powerappit@gmail.com
      from: powerappit@gmail.com
      recipients:
        - guido.fanfani7@gmail.com
        # optional: more emails here
      password:
        secretRef: smtp-password
  secrets:
  - name: smtp-password
    value: projects/archivio-valeggio/secrets/smtp-notifier-password/versions/latest